controllers:
  resource: ../../src/Controller/
  type: annotation
  locale: en
  requirements:
    _locale: "%locales%"

admin:
  resource: ../../src/Admin/
  type: annotation
  locale: en
  requirements:
    _locale: "%locales%"

easy:
  resource: ../../src/Easy
  type: annotation
  locale: en

kernel:
  resource: ../../src/Kernel.php
  type: annotation
